name: three_dart
description: three.js implement by Dart. Dart 3D library. an easy to use, lightweight, cross-platform, general purpose 3D library.
version: 0.0.16
# homepage: https://github.com/wasabia/three_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  universal_html: ^2.0.8
  ffi: ^2.0.1
  image: ^4.0.17
  flutter_gl: ^0.0.21
  crypto: ^3.0.1
  meta:

  # opentype:
  #   git: git@github.com:wasabia/opentype.git
  # typr_dart:
  #   # path: ../typr_dart
  #   git: git@github.com:wasabia/typr_dart.git
  # bidi_dart:
  #   # path: ../bidi_dart
  #   git: git@github.com:wasabia/bidi_dart.git
  # flutter_webgpu:
  #   path: ../flutter_webgpu

dependency_overrides:
  three_dart_jsm:
    git:
      url: https://github.com/2TFD/three_dart_jsm.git
  # flutter_gl:
  #   path: ../flutter_gl/flutter_gl

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
